repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        exclude: "^tests/recordings|mkdocs.yml"
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0 # should match the version specified in pyproject.toml, bump the version to avoid click 8.1.0 for the error: cannot import name '_unicodefun' from 'click'
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.941"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
#  - repo: https://github.com/PyCQA/flake8
#    rev: "3.9.0"
#    hooks:
#      - id: flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
